- name: Install Quay Service
  hosts: all
  become: yes
  tasks:
    - name: Create necessary directory for Quay local storage
        ansible.builtin.file:
          path: /etc/quay-install/quay-storage
          state: directory
          recurse: yes
          owner: root
          group: root
          mode: "0755"

    - name: Create necessary directory for Quay config bundle
        ansible.builtin.file:
          path: /etc/quay-install/quay-config
          state: directory
          recurse: yes
          owner: root
          group: root
          mode: "0755"

    - name: Set permissions on local storage directory
      ansible.posix.acl:
        path: /etc/quay-install/quay-storage
        entry: u:1001:-wx
        state: present
    
    - name: Copy Quay config.yaml file
      template: src=../templates/config.yaml dest=/etc/quay-install/quay-config

    - name: Copy Quay systemd service file
      template: src=../templates/quay.service dest=/etc/systemd/system/quay-app.service

    - name: Pull Quay image
        containers.podman.podman_image:
        name: quay.io/projectquay/quay:latest

    - name: Start Quay service
      systemd:
        name: quay-app.service
        enabled: yes
        daemon_reload: yes
        state: started
