- name: Create necessary directory for Postgres persistent data
  ansible.builtin.file:
    path: "{{ pg_storage }}"
    state: directory
    recurse: yes
  when: "pg_storage.startswith('/')"

- name: Set permissions on local storage directory
  ansible.posix.acl:
    path: "{{ pg_storage }}"
    entity: 26
    etype: user
    permissions: wx
    state: present
  when: "pg_storage.startswith('/')"

- name: Copy Postgres systemd service file
  template:
    src: ../templates/postgres.service.j2
    dest: "{{ systemd_unit_dir }}/quay-postgres.service"

- name: Check if Postgres image is loaded
  command: podman inspect --type=image {{ postgres_image }}
  register: pg
  ignore_errors: yes

- name: Pull Postgres image
  containers.podman.podman_image:
    name: "{{ postgres_image }}"
  when: pg.rc != 0
  retries: 5
  delay: 5

- name: Create Postgres Storage named volume
  containers.podman.podman_volume:
      state: present
      name: pg-storage

- name: Create Postgres Password Secret
  containers.podman.podman_secret:
    state: present
    name: pgdb_pass
    data: "{{ pgdb_password }}"

- name: Start Postgres service
  systemd:
    name: quay-postgres.service
    enabled: yes
    daemon_reload: yes
    state: restarted
    scope: "{{ systemd_scope }}"

- name: Wait for pg_trgm to be installed
  command: podman exec -it quay-postgres /bin/bash -c "echo 'CREATE EXTENSION IF NOT EXISTS pg_trgm' | psql -d quay -U postgres"
  register: result
  until: result.rc == 0
  retries: 20
  delay: 5
